# Generated by Django 2.2 on 2019-04-07 19:38

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        TrigramExtension()
    ]
